name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
    - name: Run clj tests
      run: lein cloverage --no-html
    - name: Install Karma CLI
      run: npm install -g karma-cli
    - name: Install other packages
      run: npm install
    - name: Run cljs tests
      run: lein doo once
