name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.6.1
      with:
        lein: 2.12.0
        clj-kondo: 2026.01.19
    - name: Install dependencies
      run: lein deps
    - name: Run clj tests
      run: lein cloverage --no-html
    - name: Install Karma CLI
      run: npm install -g karma-cli
    - name: Install other packages
      run: npm install
    - name: Run cljs tests
      run: lein doo once
